
import marshal, base64, zlib
exec(marshal.loads(zlib.decompress(base64.b64decode('eJx7zIAEGKH0ZwEgMZUhmEGKoYghmBFIMqYzaTInMyGpBbGZQWq5wGojGHWBtAqDJmOpApARlFqSX5SXqJCoUJyfm6iQkqqQkp9ZrJB3eFdualF+sd5KhpVMtxgTbzEmFYMMUlC4xWWTn1ZanJyYkm93iwWkqYgD6qLPnECigeEBN0+naYPPZ5DlBFzCCnWJMpJL8hUKivJTSkvyMR1TBNJdxAIkoI4pYgdSt7hyS3NKMgtyMpMTi3iAAqwgVSC3FIEs8tNkArsQLAUxASQM0cphkwu0KyfVrogX6olifiDxgZmRkfETExOj4GcOIAHWAABpgkq1')))),
